// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVG_2SZ19iqvLtt0rWDQfnxgFjFkdJEU',
    appId: '1:55596907571:web:aa0b3f6b0e4e2dab00b746',
    messagingSenderId: '55596907571',
    projectId: 'cerone-8e3f6',
    authDomain: 'cerone-8e3f6.firebaseapp.com',
    storageBucket: 'cerone-8e3f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GLPSNglUoMECY97bxFxBZHuOgV17KbU',
    appId: '1:55596907571:android:970e70a83963157e00b746',
    messagingSenderId: '55596907571',
    projectId: 'cerone-8e3f6',
    storageBucket: 'cerone-8e3f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmP-icfCfzdv9bfcYSRlPjndsndvXfkiQ',
    appId: '1:55596907571:ios:4b400b88502f620d00b746',
    messagingSenderId: '55596907571',
    projectId: 'cerone-8e3f6',
    storageBucket: 'cerone-8e3f6.appspot.com',
    iosClientId: '55596907571-klu63dl6jmecijd27ta085g0lot95hrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cerone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmP-icfCfzdv9bfcYSRlPjndsndvXfkiQ',
    appId: '1:55596907571:ios:4b400b88502f620d00b746',
    messagingSenderId: '55596907571',
    projectId: 'cerone-8e3f6',
    storageBucket: 'cerone-8e3f6.appspot.com',
    iosClientId: '55596907571-klu63dl6jmecijd27ta085g0lot95hrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cerone',
  );
}
